### PR TITLE
Changed plot

### PR DESCRIPTION
**Pull request by floridop**
Changed: opening text
Added:
  - Text about soup
  - ASCII art about soup

I was really out of ideas with these fairytale characters!

### CODE REVIEW

**Review by NJJLarsson — CHANGES_REQUESTED** [review]
Please include the type of the soup in the text file.

**Comment by floridop** [comment]
Did some minimalist change, did you want something else?

**Comment by NJJLarsson** [comment]
Looks good to me.

**Comment by floridop** [comment]
Hi! Can you perform the merge or shall I do something more? Merging will complete scenario 2.

**Comment by NJJLarsson** [comment]
Everything is good, I'll perform the merge.

**Pull request merged**
